Merge Backup to Main
komeegbedi/Route-Planner pull request #2
Opened 2024-10-16 05:00 UTC by komeegbedi

Implemented the Nearest Neighbour Heuristic in order to find the optimal route

2024-10-21 15:07 UTC, DennekJr requested changes

2024-10-21 15:07 UTC, DennekJr commented on app/components/AddressInput.jsx
> +            console.log('Processed', data.result);
no console logs

2024-10-21 15:07 UTC, DennekJr commented on app/components/AddressInput.jsx
> +    //                 console.log('Processed', data.result);
Why's this commented out instead of deleted?

2024-10-21 15:07 UTC, DennekJr commented on app/backend/processData.js
>     console.log("Optimized duration: "+ Math.ceil(optimizedTimeDuration/60));
no console logs

2024-10-21 15:07 UTC, DennekJr commented on app/backend/processData.js
>     console.log(orderOfVisit);
No console logs

2024-10-21 15:07 UTC, DennekJr commented on app/backend/processData.js
> +    isVisited[routeMetrics.durations.length - 1] = true;
it's best practice to avoid mutating state directly. Use methods that create new arrays or objects rather than directly moidying the array. 
Fro instance:
let isVisited = Array(routeMetrics.durations.length).fill(false);
isVisited = [
  ...isVisited.slice(0, routeMetrics.durations.length - 1),
  true,
];

2024-10-21 15:07 UTC, DennekJr commented on app/backend/processData.js
> +       console.log("Return Data"+ returnData);
no console.logs

2024-10-21 15:07 UTC, DennekJr commented on app/backend/processData.js
> +    // console.log(directions);
why do you have so many logs/comments lol

2024-10-21 15:07 UTC, DennekJr commented on app/backend/processData.js
> +        // console.log(address[element].value);
clean up commented out code

2024-10-21 22:22 UTC, DennekJr approved these changes

2025-03-27 05:57 UTC, komeegbedi commented
Updated design and added animations

2025-03-27 06:00 UTC, merged